### ISSUE TITLE
Cat Names Wikipedia Page

### ISSUE THREAD

**Issue by coudykid** [sckott/rforcats#21]
Hi,

It looks like the Wikipedia page has been updated. There is no longer a table under _Cultural references to the naming of cats_. When I did the tutorial I just substituted the table for Australian cat names, but I could see how this could be confusing to other users.

Anyway, thanks for a great tutorial! It really helped me out.

Thanks,

Chloe

**Comment by sckott** [comment]
hi @coudykid thanks for the issue. What wikipedia page are you talking about?  

glad you like it 😸

**Comment by StrayChild01** [comment]
Hi, I got the same error than @coudykid 

I ran this code: 

```R
library("httr")
library("rvest")

wikiCatNamePage <- GET("https://en.wikipedia.org/wiki/Popular_cat_names")
parsedWikiCatNamePage <- httr::content(wikiCatNamePage)
wikiCatNameTables <- html_table(parsedWikiCatNamePage, fill = TRUE)
```

But when I ran the code, I got a list of 5 elements instead of 6 as in the code:

![image](https://user-images.githubusercontent.com/18584930/40069125-0af77714-5830-11e8-8d6f-dff147b49818.png)

So when I run this as in the tutorial, I get:
```R
famousCats <- wikiCatNameTables[[6]]
Error in wikiCatNameTables[[6]] : subscript out of bounds
```

It is not a big issue, and I think I can propose that edit on the index.rmd file.

**Comment by sckott** [comment]
thanks @StrayChild01 , can you send a PR?

**Comment by StrayChild01** [comment]
Done.
